const ArrofObj=[
  { id:'1',
    imgsrc:"https://logodix.com/logo/1758777.jpg",
    info:"IT IS A FRAMEWORK",
    title:'DJANGO',
    link:'https://www.djangoproject.com/',
  },
  { id:'2',
    imgsrc:"https://static.geekyants.com/image-resize-cache/eyJpZCI6NjA5LCJ0IjoicmVzaXplIiwidyI6MTIwMCwiaCI6ODAwLCJxIjo5MCwidiI6MX0=.png",
    info:'IT IS A FRAMEWORK',
    title:'SVELTE',
    link:'https://svelte.dev/',
  },
  { id:'3',
    imgsrc:"https://miro.medium.com/max/2560/1*cGDDA2mfYkjiIhGaN8gDoA.png",
    info:'IT IS A FRAMEWORK',
    title:'ANGULAR',
    link:'https://angularjs.org/',
  },
  { id:'4',
    imgsrc:"https://ngninja.com/assets/posts/reactjs-102f9693a4201e678d5b02185717f4e2127d082c2f8afc0ed378cfc6cd814741.png",
    info:'IT IS A LIBRARY',
    title:'REACT',
    link:'https://reactjs.org/',
  },
  { id:'5',
    imgsrc:"https://sujanbyanjankar.com.np/wp-content/uploads/2018/05/jQuery.png",
    info:'IT IS A LIBRARY',
    title:'JQUERY',
    link:'https://jquery.com/',
  },
  { id:'6',
    imgsrc:"https://miro.medium.com/max/750/0*DwuaPR95Uig6uskm.jpg",
    info:'IT IS A LIBRARY',
    title:'D3.JS',
    link:'https://d3js.org/',
  },
]

export default ArrofObj;